### ISSUE TITLE
Function Calls vs Function Declarations

### ISSUE THREAD

**Issue by nikitaame** [kodecocodes/swift-style-guide#361]
Hello! Thank you for the great resource the team has put together! 

We're currently going through the process of adhering to the style guide. I had a question on some of the rules. IMHO there seems to be some conflict in them and I wanted to understand the reasoning behind them. Specifically, [Spacing](https://github.com/kodecocodes/swift-style-guide#spacing). What is the reason for: `Closing parentheses should not appear on a line by themselves.`?

This is preferred:
```
let user = try await getUser(
  for: userID,
  on: connection)
```
over:
```
let user = try await getUser(
  for: userID,
  on: connection
)
```

Why should the parentheses be on the same line as the last parameter? IHMO, something where closing braces (and parentheses) should line up with the indentation of the line that contains the opening brace becomes more consistent and readable. 

This might also better match up with other rules such as [Function Calls](https://github.com/kodecocodes/swift-style-guide#function-declarations) where the parentheses is on its own line.

Looking around, it looks like other folks go by this standard as well. Examples in this [discussion](https://github.com/kodecocodes/swift-style-guide/issues/284).

**Comment by rcritz** [comment]
Remember that our style guide is built for publishing tutorials and books. As a result, space matters and this is a case where we felt it was appropriate to specify this as our style.

**Comment by nikitaame** [comment]
That makes sense in this context! Thank you so much!
